# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-27 03:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0003_auto_20180503_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_favorite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
