# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-27 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20180627_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
