# Generated by Django 2.1.3 on 2018-11-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20181125_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
